### ISSUE TITLE
Aborting program before MQTT is actually connected panics

### ISSUE THREAD

**Issue by maddie** [eclipse/paho.mqtt.golang#103]
My code is roughly like:

```
client := mqtt.NewClient(opts)
client.Connect()
defer client.Disconnect(0)

# blocking channel that receives a signal when program is shutting down
<-wait
```

Output:

```
panic: close of nil channel

goroutine 34 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).closeStop(0xc420078e00)
        /src/github.com/eclipse/paho.mqtt.golang/client.go:455 +0x13a
github.com/eclipse/paho%2emqtt%2egolang.(*client).disconnect(0xc420078e00)
        /src/github.com/eclipse/paho.mqtt.golang/client.go:468 +0x2f
github.com/eclipse/paho%2emqtt%2egolang.(*client).Disconnect(0xc420078e00, 0x0)
        /github.com/eclipse/paho.mqtt.golang/client.go:413 +0x270
```

On line 455 of `client.go`, `closeStop` tries to close channel `c.stop`, which might not be initialized when MQTT client is not connected to the endpoint (i.e. due to connectivity problem). If program is getting terminated (i.e. `Ctrl + C`) it will panic because it's closing a nil channel.

**Comment by maddie** [comment]
Seems to be something wrong with my end.. closing it for now.
