### ISSUE TITLE
Panic when "pingresp not received"

### ISSUE THREAD

**Issue by xapon** [eclipse/paho.mqtt.golang#127]
After a today's update (https://github.com/eclipse/paho.mqtt.golang/commit/ad6f78e8ed29b35fed641a4febe25d47d008260a), I'm receiving a panic after a client detects ping timeout:

The full error stack looks like this
```
 time="2017-07-28T23:39:46Z" level=warning msg="MQTT connection lost pingresp not received, disconnecting"
server_1   | panic: sync: negative WaitGroup counter
server_1   |
server_1   | goroutine 16 [running]:
server_1   | sync.(*WaitGroup).Add(0xc420274304, 0xffffffffffffffff)
server_1   |    /usr/local/go/src/sync/waitgroup.go:75 +0x1c9
server_1   | sync.(*WaitGroup).Done(0xc420274304)
server_1   |    /usr/local/go/src/sync/waitgroup.go:100 +0x34
server_1   | github.com/eclipse/paho%2emqtt%2egolang.keepalive.func1(0xc420174000, 0xc42011ac40)
server_1   |    /go/src/github.com/eclipse/paho.mqtt.golang/ping.go:35 +0x8a
server_1   | github.com/eclipse/paho%2emqtt%2egolang.keepalive(0xc420174000)
server_1   |    /go/src/github.com/eclipse/paho.mqtt.golang/ping.go:113 +0x747
server_1   | created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
server_1   |    /go/src/github.com/eclipse/paho.mqtt.golang/client.go:246 +0xe24
```

First line is my application's log (MQTT connection lost), then error text from mqtt library goes (pingresp not received, disconnecting), then it panics.

I'm using the following settings:
Keepalive = 2 seconds
Ping timeout = 2 seconds
AutoReconnect = true

**Comment by nickw444** [comment]
Just chiming in here to say i'm also having this exact issue:

```
panic: sync: negative WaitGroup counter

goroutine 10 [running]:
sync.(*WaitGroup).Add(0x10b421d0, 0xffffffff)
        /usr/local/go/src/sync/waitgroup.go:75 +0x1cc
sync.(*WaitGroup).Done(0x10b421d0)
        /usr/local/go/src/sync/waitgroup.go:100 +0x24
github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho%2emqtt%2egolang.keepalive.func1(0x10ac2000, 0x10cdeab0)
        /Users/nickw/go/src/github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho.mqtt.golang/ping.go:35 +0x7c
github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho%2emqtt%2egolang.keepalive(0x10ac2000)
        /Users/nickw/go/src/github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho.mqtt.golang/ping.go:113 +0x5d8
created by github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
        /Users/nickw/go/src/github.com/nickw444/homekit/bridge/vendor/github.com/eclipse/paho.mqtt.golang/client.go:246 +0xbe4
```

**Comment by alsm** [comment]
Very sorry about that, my mistake, should be resolved now. Thanks for reporting.
