### ISSUE TITLE
Latest commit breaks functionality on 32 bit raspberrypi

### ISSUE THREAD

**Issue by sanket28** [eclipse/paho.mqtt.golang#136]
Here's the stack trace:

```
goroutine 33 [running]:
sync/atomic.storeUint64(0x107383d4, 0x5995eaa2, 0x0)
  /usr/local/go/src/sync/atomic/64bit_arm.go:20 +0x3c
github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1(0x10738200, 0x10734020, 0x10710060)
  /Users/jim/Documents/AppDev/GoLang/workspace/src/github.com/eclipse/paho.mqtt.golang/client.go:242 +0x920
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect
  /Users/jim/Documents/AppDev/GoLang/workspace/src/github.com/eclipse/paho.mqtt.golang/client.go:275 +0x124
```

**Comment by sdariz** [comment]
Same thing with my board : 64bits not supported

**Comment by alsm** [comment]
So it seems that on ARM and x86-32 it was down to me to 64 bit align the int64s I was using, the latest commit should do this, please try and let me know.

**Comment by sdariz** [comment]
It's OK on my ARM 32bits. Thanks.

**Comment by alsm** [comment]
I'm going to close this as resolved now
