### ISSUE TITLE
publish panic:close of closed channel

### ISSUE THREAD

**Issue by autofit** [eclipse/paho.mqtt.golang#145]
---- doing publish ----
panic: close of closed channel

goroutine 1 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).disconnect(0xc42006ea80)
	/users/xuwenxiang/cofjs/src/github.com/eclipse/paho.mqtt.golang/client.go:475 +0x66
github.com/eclipse/paho%2emqtt%2egolang.(*client).Disconnect(0xc42006ea80, 0xfa)
	/users/xuwenxiang/cofjs/src/github.com/eclipse/paho.mqtt.golang/client.go:414 +0x270
main.main()
	/users/xuwenxiang/cofjs/testup.go:828 +0x2565
exit status 2

Located at client.go 475:close(c.stopRouter)

**Comment by autofit** [comment]
error :close chan myself
