### ISSUE TITLE
Disconnect() needs to cause messageid cleanUp()

### ISSUE THREAD

**Issue by danielbprice** [eclipse/paho.mqtt.golang#169]
I believe I am seeing a race between Publish() and Disconnect().  Below are some traces I gathered.  My application is publishing periodic messages to Google IoT core.  Google's JWT authentication requires periodic refresh and reconnect, so my client needs to sometimes do that-- and due to the issue documented in #147, on a timer, I have to change the options, tear the client down completely and swap in a new client.  In my testing, some sort of race between Disconnect() and Publish() seems to happen fairly often.  I can work around this by adding locking atop this library but that's not ideal.

Here is a trace of mqtt and my application.  In this case, the message to the IoT core is called an "Upbeat."

```
2017-12-21T21:45:22.174Z        INFO    paho.mqtt.golang/ping.go:46     [pinger]   ping check 60
2017-12-21T21:45:22.203Z        INFO    iot.go:100       sendUpbeat
2017-12-21T21:45:22.203Z        INFO    iot.go:120       Sending upbeat  {"text": "REDACTED"}
2017-12-21T21:45:22.203Z        INFO    paho.mqtt.golang/client.go:488  [client]   enter Publish
2017-12-21T21:45:22.203Z        INFO    paho.mqtt.golang/client.go:513  [client]   sending publish message, topic: /devices/xxx/events/upbeat
2017-12-21T21:45:22.203Z        INFO    paho.mqtt.golang/net.go:190     [net]      obound wrote msg, id: 1
2017-12-21T21:45:22.203Z        INFO    paho.mqtt.golang/net.go:163     [net]      outgoing waiting for an outbound message
2017-12-21T21:45:22.209Z        INFO    iotcore/iotcore.go:63   refreshJWT()
2017-12-21T21:45:22.213Z        INFO    iotcore/iotcore.go:80   refreshJWT() disconnecting client
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/client.go:403  [client]   disconnecting
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/net.go:198     [net]      obound priority msg to write, type *packets.DisconnectPacket
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/net.go:207     [net]      outbound wrote disconnect, stopping
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/net.go:146     [net]      incoming stopped
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/ping.go:43     [pinger]   keepalive stopped
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/net.go:316     [net]      logic stopped
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/client.go:479  [client]   disconnected
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/memstore.go:126        [store]    memorystore closed
2017-12-21T21:45:22.213Z        INFO    iotcore/iotcore.go:85   refreshJWT() reconnecting client
2017-12-21T21:45:22.213Z        INFO    paho.mqtt.golang/client.go:164  [client]   Connect()
```

My publish codepath looks like this:

```go
        slogger.Infow("Sending upbeat", "text", string(text))
        t := iotc.PublishEvent("upbeat", 1, text)
        if t.Wait() {
                slogger.Infow("Sent upbeat", "text", string(text))
                return nil
        } else {
                slogger.Errorw("upbeat failed", "error", string(t.Error()))
                return errors.Wrap(t.Error(), "Failed to wait for upbeat publish")
        }
```

PublishEvent() is a trivial wrapper around Publish: 
```go
// PublishEvent publishes an event ('telemetry') to the IoT core broker
func (c *IoTMQTTClient) PublishEvent(subfolder string, qos byte, payload interface{}) mqtt.Token {
          if subfolder != "" {
                  return c.Publish(c.eventTopic+"/"+subfolder, qos, false, payload)
          } else {
                  return c.Publish(c.eventTopic, qos, false, payload)
          }
  }
```

What I see here is that when the `Publish()` and `Disconnect()` happen at approximately the same time (see above, about 10ms apart, with activity from each overlapping) the token `Wait()` for the `Publish()` never seems to complete.  I enabled GOTRACEBACK=2 and captured the following trace of what my code is doing-- as expected, it's stuck on a token `Wait()`.  Dunno if that helps:

```
goroutine 1 [chan receive, 176 minutes]:
runtime.gopark(0x8f5668, 0xc4204295b8, 0x8dc724, 0xc, 0xc420237817, 0x3)
        .../go/src/runtime/proc.go:271 +0x13a fp=0xc4200479a8 sp=0xc420047978
runtime.goparkunlock(0xc4204295b8, 0x8dc724, 0xc, 0x8dd017, 0x3)
        .../go/src/runtime/proc.go:277 +0x5e fp=0xc4200479e8 sp=0xc4200479a8
runtime.chanrecv(0x81cee0, 0xc420429560, 0x0, 0xc420433a01, 0xc4203e6c00)
        .../go/src/runtime/chan.go:513 +0x371 fp=0xc420047a88 sp=0xc4200479e8
runtime.chanrecv1(0x81cee0, 0xc420429560, 0x0)
        .../go/src/runtime/chan.go:395 +0x35 fp=0xc420047ac0 sp=0xc420047a88
bg/vendor/github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).Wait(0xc420011e40, 0x8d8800)
        /<redacted>/golang/src/bg/vendor/github.com/eclipse/paho.mqtt.golang/token.go:57 +0xa5 fp=0xc420047ae8 sp=0xc420047ac0
main.sendUpbeat(0xc42012a000, 0xc4202e1e60, 0xc420433d08)
        /<redacted>/iot.go:122 +0x52f fp=0xc420047c88 sp=0xc420047ae8
main.upbeatLoop(0xc42012a000)
        /<redacted>/iot.go:159 +0x2cd fp=0xc420047e28 sp=0xc420047c88
main.main()
        /<redacted>/iot.go:235 +0x458 fp=0xc420047f88 sp=0xc420047e28
runtime.main()
        .../go/src/runtime/proc.go:185 +0x20a fp=0xc420047fe0 sp=0xc420047f88
runtime.goexit()
        .../go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420047fe8 sp=0xc420047fe0
```

So is this expected?  The semantics of when Wait() would return False don't seem well documented, but I had assumed (big mistake, maybe) that on connection disconnect, all waiters would be awoken with a False result.

**Comment by danielbprice** [comment]
FWiW I am calling Disconnect(1000) to try to give things time to drain out.  The reconnect logic looks like this:

```go
          connected := c.Client.IsConnected()
          if connected {
                  // So instead we disconnect, make a new client, and reconnect
                  log.Printf("refreshJWT() disconnecting client\n")
                  c.Client.Disconnect(1000)
          }
          // manufacture new client and swap it in place of the old.
          c.makeClient()
          if connected {
                  log.Printf("refreshJWT() reconnecting client\n")
                  if token := c.Client.Connect(); token.Wait() && token.Error() != nil {
                          panic(token.Error())
                  }
                  log.Printf("refreshJWT() reconnected client\n")
          }
```

Maybe the answer is to go tackle #147 but I'm not confident in my ability to modify this code without breaking it.

**Comment by danielbprice** [comment]
Maybe the answer is c.messageIds.cleanUp() on Disconnect?

**Comment by alsm** [comment]
I think this might be to do with me expecting that if you are using persistent sessions (cleansession false) then missing confirmations to publishes should be resent by the server, but I realise this will only happen with QoS2 where the sender has received PUBREC. I think you're right that the easiest thing to do for now is mark all outstanding tokens as errored when disconnecting.

**Comment by alsm** [comment]
Thanks for reporting, should be resolved in 0a1518b02ff59b85415088f7b632c5c8eeb35d55

**Comment by danielbprice** [comment]
Thanks for your response.  In my case, however CleanSession is set to true, I believe.  Regardless, I will try this patch today.  I will see what happens.  Thanks!

Here is my client setup code:
```golang
        // Setup MQTT client options
        opts := mqtt.NewClientOptions().AddBroker(cMQTTBrokerURI)
        opts.SetKeepAlive(cMQTTKeepAlive)

        opts.SetPingTimeout(cMQTTPingTimeout)

        opts.SetUsername(.....)
        opts.SetPassword(.....)
        opts.SetClientID(......)

        mqttc := mqtt.NewClient(opts)
```

**Comment by danielbprice** [comment]
I updated my code to HEAD on master, and re-ran the same stress test I have been using.  I saw the same hang, wherein my publish never completed.  Here's a log.  You can see that the disconnect starts almost immediately after the publish request is made.

```
2018-01-09T19:20:23.393Z        INFO    paho.mqtt.golang/client.go:483  [client]   enter Publish
2018-01-09T19:20:23.393Z        INFO    paho.mqtt.golang/client.go:508  [client]   sending publish message, topic: /devices/dp-pi/events/upbeat
2018-01-09T19:20:23.393Z        INFO    paho.mqtt.golang/net.go:190     [net]      obound wrote msg, id: 1
2018-01-09T19:20:23.393Z        INFO    paho.mqtt.golang/net.go:163     [net]      outgoing waiting for an outbound message
2018-01-09T19:20:23.401Z        INFO    iotcore/iotcore.go:73   refreshJWT()
2018-01-09T19:20:23.405Z        INFO    iotcore/iotcore.go:92   refreshJWT() disconnecting client
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/client.go:400  [client]   disconnecting
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/net.go:198     [net]      obound priority msg to write, type *packets.DisconnectPacket
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/net.go:207     [net]      outbound wrote disconnect, stopping
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/net.go:146     [net]      incoming stopped
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/net.go:316     [net]      logic stopped
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/ping.go:43     [pinger]   keepalive stopped
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/net.go:326     [net]      errorWatch stopped
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/client.go:474  [client]   disconnected
2018-01-09T19:20:23.406Z        INFO    paho.mqtt.golang/memstore.go:126        [store]    memorystore closed
2018-01-09T19:20:23.406Z        INFO    iotcore/iotcore.go:97   refreshJWT() reconnecting client
```

**Comment by danielbprice** [comment]
As an experiment I added `c.messageIds.cleanUp()` to `disconnect()`.  I'll let it run for a couple of hours.

**Comment by alsm** [comment]
Ahh, just realised yeah, the change I made was in internalConnLost() so it wouldn't have changed your situation, please let me know if the change you've made has resolved the issue

**Comment by danielbprice** [comment]
Yes, I've had my stress test running for an hour, and I'm seeing Tokens error out as I would expect, instead of hanging.   The change I made is:

```diff
  func (c *client) disconnect() {
          c.closeStop()
          c.closeConn()
          c.workers.Wait()
+         c.messageIds.cleanUp()
          close(c.stopRouter)
          DEBUG.Println(CLI, "disconnected")
          c.persist.Close()
  }```

I think I have a pull request nearly ready.
