### ISSUE TITLE
Websocket connections returning Bad Status on many brokers

### ISSUE THREAD

**Issue by senorequeso** [eclipse/paho.mqtt.golang#215]
I'm having trouble connecting a client to a broker via websockets. It says it is supported by the library but most brokers I've tried return "bad status". I am testing using the [simple example](https://github.com/eclipse/paho.mqtt.golang/blob/master/cmd/simple/main.go) found in the repository, substituting the broker for various brokers supporting websockets as listed here: https://github.com/mqtt/mqtt.github.io/wiki/public_brokers

Examples:
`ws://test.mosquitto.org:80`:
```
[daniel@archbook test]$ go run main.go 
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   websocket.Dial ws://test.mosquitto.org:80: bad status
[client]   Failed to connect to a broker
[store]    memorystore closed
panic: Network Error : websocket.Dial ws://test.mosquitto.org:80: bad status

goroutine 1 [running]:
main.main()
	/home/daniel/go/src/zebra.farm/test/main.go:40 +0x702
exit status 2
```
`ws://iot.eclipse.org:80`:
```
[daniel@archbook test]$ go run main.go 
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   websocket.Dial ws://iot.eclipse.org:80: bad status
[client]   Failed to connect to a broker
[store]    memorystore closed
panic: Network Error : websocket.Dial ws://iot.eclipse.org:80: bad status

goroutine 1 [running]:
main.main()
	/home/daniel/go/src/zebra.farm/test/main.go:40 +0x702
exit status 2
```

This one, however, seems to work:
`ws://mqtt.flespi.io:80`:
```
[daniel@archbook test]$ go run main.go 
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
[net]      connect started
[net]      received connack
[client]   Trying reconnect using MQTT 3.1 protocol
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1 protocol
[net]      connect started
[net]      received connack
[client]   Failed to connect to a broker
[store]    memorystore closed
panic: Not Authorized
```
as well as
`ws://broker.hivemq.com:8000`:
```
[daniel@archbook test]$ go run main.go 
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   websocket.Dial ws://broker.hivemq.com:8000: unexpected EOF
[client]   Failed to connect to a broker
[store]    memorystore closed
panic: Network Error : websocket.Dial ws://broker.hivemq.com:8000: unexpected 
```

Please let me know if I am doing something obviously incorrect or what more information you might need from me. For posterity:

```[daniel@archbook test]$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/daniel/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/daniel/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build366887069=/tmp/go-build -gno-record-gcc-switches"
```
and I am using the latest version of the library pulled today.

Thanks!

**Comment by senorequeso** [comment]
Couldn't stop thinking about this issue all day. I ran some more tests to try and narrow down what I might be seeing. Unfortunately, the results of my testing do not bode well for my theory.

I retested all the brokers on the public_brokers list using three different clients (slight variations off of normal simple client examples): 
* a [Python client](https://gist.github.com/96d39ed333aacedcb655dc04f7070796)
* a [JavaScript client](https://gist.github.com/70b42789c107a99b9d9f8fa0017532de)
* the [Go client](https://gist.github.com/f26a0e21af0ab3f685af20178ea734f5)

Here are the results:

| Host                          | Python | JavaScript | Go    |
|-------------------------------|--------|------------|-------|
| ws://mqtt.flespi.io:80        | Pass   | Error      | Pass  |
| ws://iot.eclipse.org:80       | Error  | Pass       | Error |
| ws://test.mosquitto.org:80    | Error  | Pass       | Error |
| ws://broker.hivemq.com:8000   | Pass   | Pass       | Pass  |
| ws://mqtt.dioty.co:8080       | Pass   | Error      | Pass  |
| ws://broker.bevywise.com:8443 | Pass   | Pass       | Pass  |

Unfortunately, this does not get me any closer to understanding why I'm receiving a "Bad Status" response from my internal MQTT service.

**Comment by senorequeso** [comment]
Update: as it would turn out (and was pointed out to me), most of these addresses require an additional path after the URL for websocket connections. It would appear that the Java and Python clients ado this internally (and the JS one does it in the examples, I had just not nocied it) and I hadn't realized that the Go client simply doesn't.

Python: https://github.com/eclipse/paho.mqtt.python/blob/master/src/paho/mqtt/client.py#L572
Java: https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/internal/websocket/WebSocketHandshake.java#L87

Therefore, there is no bug, I was just using the client wrong. I'll close this issue but leave it up in case someone else has the same misunderstanding I did.
