### ISSUE TITLE
Client connects and disconnects immediately under heavy data load

### ISSUE THREAD

**Issue by ricardoatsouza** [eclipse/paho.mqtt.golang#261]
In one of our MQTT topics, we have a big data load (it peaks daily up to ~500 thousand per second). Our services subscribe to the topic, consume the message and sends it forward to the next topic. So far so good.

But over the last few weeks we started having an issue in which the services would connect and immediately disconnect from MQTT, and would keep on going on this behaviour. It only stabilises when the data load goes down to ~50 k per sec.

The service generates logs of each action. I am pasting one second of it here:

```bash
2018-11-16 13:37:29.453452476 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (read tcp xx.xxx.xxx.xx:39028->yy.yyy.yy.y:1883: read: connection reset by peer)
2018-11-16 13:37:29.45350104 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.453587427 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.459863991 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.459912734 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.460987964 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (write tcp xx.xxx.xxx.xx:39030->yy.yyy.yy.y:1883: write: connection reset by peer)
2018-11-16 13:37:29.461533734 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.46155436 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.46156167 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.461682074 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.461738512 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.461759996 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.463074471 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.467228301 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.467375901 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.468004815 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (write tcp xx.xxx.xxx.xx:39032->yy.yyy.yy.y:1883: write: connection reset by peer)
2018-11-16 13:37:29.468177718 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (write tcp xx.xxx.xxx.xx:39032->yy.yyy.yy.y:1883: write: connection reset by peer)
2018-11-16 13:37:29.46880864 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.468832454 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.472224506 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.472318773 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.476295518 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (read tcp xx.xxx.xxx.xx:39034->yy.yyy.yy.y:1883: read: connection reset by peer)
2018-11-16 13:37:29.476394484 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.476411008 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.476560489 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.476631269 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.480995776 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.481083808 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.482655866 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.482725477 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.48279398 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (read tcp xx.xxx.xxx.xx:39036->yy.yyy.yy.y:1883: read: connection reset by peer)
2018-11-16 13:37:29.482966175 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.483027196 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.498105777 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.498231437 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.498507162 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (write tcp xx.xxx.xxx.xx:39036->yy.yyy.yy.y:1883: use of closed network connection)
2018-11-16 13:37:29.502856909 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.502941101 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.5042236 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (read tcp xx.xxx.xxx.xx:39040->yy.yyy.yy.y:1883: read: connection reset by peer)
2018-11-16 13:37:29.50425987 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.504272247 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.504283283 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.504303737 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.504313607 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.512870907 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.512920036 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.513952429 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (write tcp xx.xxx.xxx.xx:39042->yy.yyy.yy.y:1883: write: connection reset by peer)
2018-11-16 13:37:29.514066059 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.514702378 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.52278448 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.522893894 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.524128057 +0000 UTC MqttBrokerConnection [Error]: Connection lost with Mqtt (read tcp xx.xxx.xxx.xx:39044->yy.yyy.yy.y:1883: read: connection reset by peer)
2018-11-16 13:37:29.52433204 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.524418582 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.524483142 +0000 UTC main [Error]: Error when subscribing to topic "topic-1/#" (Connection lost before Subscribe completed)
2018-11-16 13:37:29.52450521 +0000 UTC main [Info]: Subscribing to topic "topic-2/#"
2018-11-16 13:37:29.531214022 +0000 UTC MqttBrokerConnection [Debug]: Connected with Mqtt
2018-11-16 13:37:29.531255707 +0000 UTC main [Info]: Subscribing to topic "topic-1/#"
2018-11-16 13:37:29.533040117 +0000 UTC main [Error]: Error when subscribing to topic "topic-2/#" (Connection lost before Subscribe completed)
```

We are basically scoring records of reconnections per second ;)

First, we started investigating our services to make sure that there is no problem on our side. Then we started checking the library. We found out that, by using this version of the paho library, ae8614d9932c5135f2f24fe4a989dd5214a00171 (by coincidence one that I contributed to), the same problem would not happen.

The failing services were built on 31-Oct, and the biggest commit back then happened on 25-oct (67becfbf9c5739a6cabb7e1eee2e31499d88869e). So we are guessing that some sort of racing condition must be happening. 

Also, interesting enough, that commit also introduced a new error:
```
        panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x89d12c]

        goroutine 125105 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).resume(0xc00038e000, 0x9f2600)
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:657 +0xdc
github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect(0xc00038e000)
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:430 +0x110f
        created by github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:507 +0xd7
```

I am not sure of what is actually happening (or if the `panic` above is related), and I am opening this issue so we can discuss more about it. I will keep investigating though. If I find out what is happening, I am more than happy to create PR to fix it.

Sorry for the loads of information in the ticket. :)

Thanks

**Comment by alsm** [comment]
Is there any indication from the server logs as to why the connection is being dropped? Unfortunately the advice in the spec for pretty much all issues is for the server to drop the connection. It would seem from the logs that there is a subscribe being issued by the client that the server does not like, but it's not possible to tell from the logs why that is.

**Comment by ricardoatsouza** [comment]
Hi @alsm , thanks for the answer.

I couldn't detect anything unusual in the server back then. And whatever error comes back fro the library, it's being printed in the logs you see. 

I am aware this is not enough information, but the issue got fixed when we rollback the version of the library in our services. So far, they have been operating normally. 

That's why this led to the (maybe mistaken) assumption that there might be something wrong with the library, since it was the only thing we changed to fix it. 

Unfortunately I haven't had time to look deeper into the library (I actually like doing this kind of stuff, but it's a matter of time). We are fixing some other issues in our product at the moment, but we will upgrade the library to the latest version again soon (and we should face the issue once more).

I will keep this issue updated with new relevant info as soon as I have any. Meanwhile, if you (or someone) have any ideas on where to investigate or experience the same thing, would be nice to post it here. :)

Thanks.

**Comment by alsm** [comment]
I'm guessing but I think the problem is something to do with the resume() call at the end of the reconnect() function. The connections that you have, are they cleansession true or false?

**Comment by VieYang** [comment]
I have the same error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x89d12c]

goroutine 125105 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*client).resume(0xc00038e000, 0x9f2600)
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:657 +0xdc
github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect(0xc00038e000)
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:430 +0x110f
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost
            /go/src/github.com/eclipse/paho.mqtt.golang/client.go:507 +0xd7
```

**Comment by MattBrittan** [comment]
Closing due to age/inactivity. Please feel free to reopen if this issue is occurring with the current release.
