### ISSUE TITLE
isn't working after "go mod init" .. whats wrong?

### ISSUE THREAD

**Issue by slaesh** [eclipse/paho.mqtt.golang#435]
it works fine, but if i want to use the go modules in my project, it stops working!

<pre><span style="background-color:#3F3F3F"> </span><span style="background-color:#3F3F3F"><font color="#DFAF8F">sascha </font></span><span style="background-color:#9AB8D7"><font color="#3F3F3F"> ~/work/go/mqtt_test </font></span><font color="#9AB8D7"></font> <font color="#60B48A">go</font> run <u style="text-decoration-style:single">main.go</u>                                                                             <font color="#705050"></font><span style="background-color:#705050"><font color="#FFFF00"> 1 ↵ </font></span><span style="background-color:#705050"><font color="#DCDCDC"></font></span><span style="background-color:#DCDCDC"><font color="#3F3F3F"> 10:55:56</font></span>
Connected to server
OnConnect cb!
^Csignal: interrupt
<span style="background-color:#3F3F3F"> </span><span style="background-color:#3F3F3F"><font color="#DFAF8F">sascha </font></span><span style="background-color:#9AB8D7"><font color="#3F3F3F"> ~/work/go/mqtt_test </font></span><font color="#9AB8D7"></font> <font color="#60B48A">go</font> mod init mqtt_test                                                                      <font color="#705050"></font><span style="background-color:#705050"><font color="#FFFF00"> 1 ↵ </font></span><span style="background-color:#705050"><font color="#DCDCDC"></font></span><span style="background-color:#DCDCDC"><font color="#3F3F3F"> 10:58:19</font></span>
go: creating new go.mod: module mqtt_test
<span style="background-color:#3F3F3F"> </span><span style="background-color:#3F3F3F"><font color="#DFAF8F">sascha </font></span><span style="background-color:#9AB8D7"><font color="#3F3F3F"> ~/work/go/mqtt_test </font></span><font color="#9AB8D7"></font> <font color="#60B48A">go</font> run <u style="text-decoration-style:single">main.go</u>                                                                               <font color="#3F3F3F"></font><span style="background-color:#3F3F3F"><font color="#60B48A"> ✔ </font></span><span style="background-color:#3F3F3F"><font color="#DCDCDC"></font></span><span style="background-color:#DCDCDC"><font color="#3F3F3F"> 10:58:34</font></span>
go: finding module for package github.com/eclipse/paho.mqtt.golang
go: finding module for package golang.org/x/net/ipv6
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: found github.com/eclipse/paho.mqtt.golang in github.com/eclipse/paho.mqtt.golang v1.2.0
go: found golang.org/x/net/ipv6 in golang.org/x/net v0.0.0-20200625001655-4c5254603344
could not connect:
panic: Network Error : Unknown protocol

goroutine 1 [running]:
main.initMqtt()
        /home/sascha/work/go/mqtt_test/main.go:45 +0x3c9
main.main()
        /home/sascha/work/go/mqtt_test/main.go:121 +0x2b0
exit status 2
</pre>

<pre><span style="background-color:#3F3F3F"> </span><span style="background-color:#3F3F3F"><font color="#DFAF8F">sascha </font></span><span style="background-color:#9AB8D7"><font color="#3F3F3F"> ~/work/go/coap2mqtt </font></span><font color="#9AB8D7"></font> <font color="#60B48A">go</font> version                                                                                 <font color="#705050"></font><span style="background-color:#705050"><font color="#FFFF00"> 1 ↵ </font></span><span style="background-color:#705050"><font color="#DCDCDC"></font></span><span style="background-color:#DCDCDC"><font color="#3F3F3F"> 10:58:45</font></span>
go version go1.14.4 linux/amd64</pre>

```golang
func initMqtt() {
	opts := MQTT.NewClientOptions().AddBroker("***")
	opts.SetClientID("xyz")
	opts.SetDefaultPublishHandler(f)
	opts.SetUsername("***")
	opts.SetPassword("***")

	opts.OnConnect = func(c MQTT.Client) {
		//if token := c.Subscribe(topic, 0, f); token.Wait() && token.Error() != nil {
		//	panic(token.Error())
		//}
		fmt.Println("OnConnect cb!")
	}

	client = MQTT.NewClient(opts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		fmt.Println("could not connect:")
		panic(token.Error())
	} else {
		fmt.Printf("Connected to server\n")
	}
}
```

**Comment by slaesh** [comment]
`go get github.com/eclipse/paho.mqtt.golang@master` did the trick!

thanks
