### ISSUE TITLE
go test connection refused error

### ISSUE THREAD

**Issue by ap1904** [eclipse/paho.mqtt.golang#513]
Hello I'm new to golang and I needed this package to run a MQTT client for a project. When I did "go test", I m getting the following error. I wish you help me resolve this error.
```
FAIL: Test_Start (0.00s)
    fvt_client_test.go:31: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Disconnect (0.00s)
    fvt_client_test.go:113: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Publish_1 (0.00s)
    fvt_client_test.go:141: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Publish_2 (0.00s)
    fvt_client_test.go:157: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Publish_3 (0.00s)
    fvt_client_test.go:174: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Publish_BytesBuffer (0.00s)
    fvt_client_test.go:192: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Subscribe (0.00s)
    fvt_client_test.go:220: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Will (0.00s)
    fvt_client_test.go:260: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_CleanSession (0.00s)
    fvt_client_test.go:304: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_Binary_Will (0.00s)
    fvt_client_test.go:378: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p0s0 (0.00s)
    fvt_client_test.go:438: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p0s1 (0.00s)
    fvt_client_test.go:484: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p0s2 (0.00s)
    fvt_client_test.go:530: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p1s0 (0.00s)
    fvt_client_test.go:577: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p1s1 (0.00s)
    fvt_client_test.go:624: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p1s2 (0.00s)
    fvt_client_test.go:670: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p2s0 (0.00s)
    fvt_client_test.go:717: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p2s1 (0.00s)
    fvt_client_test.go:762: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_p2s2 (0.00s)
    fvt_client_test.go:809: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_PublishMessage (0.00s)
    fvt_client_test.go:858: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_PublishEmptyMessage (0.00s)
    fvt_client_test.go:906: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_MultipleURLs (0.00s)
    fvt_client_test.go:1005: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_ping1_idle5 (0.00s)
    fvt_client_test.go:1028: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_autoreconnect (0.00s)
    fvt_client_test.go:1047: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_cleanUpMids (0.00s)
    fvt_client_test.go:1074: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
--- FAIL: Test_cleanUpMids_2 (0.00s)
    fvt_client_test.go:1124: Error on Client.Connect(): network Error : dial tcp 127.0.0.1:1883: connect: connection refused
panic: test timed out after 10m0s

goroutine 1319 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001d2780, 0x7a9292, 0x11, 0x7c29e8, 0x48fa00)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000001b00)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000001b00, 0xc000159de0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00000e0d8, 0x9d1ec0, 0x69, 0x69, 0xc028bad0f03d3477, 0x8bb2d15169, 0x9d5ae0, 0x7a79c4)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc00015c600, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:251 +0x138

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f22fa1daf70, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000da018, 0x72, 0x0, 0x0, 0x7a51c0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0000da000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc0000da000, 0x30, 0x30, 0x7f2323ccf5b8)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000a8030, 0xc000050df0, 0x40fef8, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000a8030, 0x77d840, 0xc00009a540, 0x7436c0, 0x9c6f40)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00008e000, 0x817ca0, 0xc0000a8030, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2981 +0x285
net/http.(*Server).ListenAndServe(0xc00008e000, 0xc00008e000, 0x0)
	/usr/local/go/src/net/http/server.go:2910 +0xba
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3164
github.com/eclipse/paho%2emqtt%2egolang.init.1.func1()
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/unit_client_test.go:32 +0x58
created by github.com/eclipse/paho%2emqtt%2egolang.init.1
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/unit_client_test.go:31 +0x35

goroutine 107 [chan receive]:
github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).Wait(0xc0001b4600, 0xc00001a200)
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/token.go:73 +0x38
github.com/eclipse/paho%2emqtt%2egolang.Test_ConnectRetry(0xc0001d2780)
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/fvt_client_test.go:1161 +0x28a
testing.tRunner(0xc0001d2780, 0x7c29e8)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3

goroutine 108 [sleep]:
time.Sleep(0x1dcd6500)
	/usr/local/go/src/runtime/time.go:193 +0xd2
github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1(0xc0001cd8c0, 0xc0001b4600)
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/client.go:278 +0x1da
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect
	/home/astroboy/go/pkg/mod/github.com/eclipse/paho.mqtt.golang@v1.3.4/client.go:264 +0x171
exit status 2
FAIL	github.com/eclipse/paho.mqtt.golang	600.008s
```

**Comment by MattBrittan** [comment]
The tests require a broker - see [this readme](https://github.com/eclipse/paho.mqtt.golang/tree/master/fvt) for more info (the documentation for this is not great). I generally use Mosquitto running under docker for this (see the [docker](folder)).

**Comment by MattBrittan** [comment]
Closing this due to the lack of a response to my comment (which I'm fairly sure points out the solution).
