### ISSUE TITLE
client.Disconnect() panics when client tries to reconnect

### ISSUE THREAD

**Issue by anymark** [eclipse/paho.mqtt.golang#56]
When client tries to reconnect after lost connection to the broker, calling `client.Disconnect()` causes panic in https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L441, because `c.conn` is `nil` even when `client.IsConnected()` reports `true`.

Explicit check for `nil` value avoids the panic, but I'm not sure it cures the root cause.

```
func (c *client) disconnect() {
	c.closeStop()
	if c.conn != nil {
		c.conn.Close()
	}
	c.workers.Wait()
	close(c.stopRouter)
	DEBUG.Println(CLI, "disconnected")
	c.persist.Close()
}
```

versions:
```
mosquitto version 1.4.8 (build date Sun, 14 Feb 2016 15:06:55 +0000)
go version go1.7 linux/amd64
```

test case:
```
package main

import (
	"log"
	"os"
	MQTT "github.com/eclipse/paho.mqtt.golang"
)

func main() {
	MQTT.ERROR = log.New(os.Stdout, "", 0)
	MQTT.WARN = log.New(os.Stdout, "", 0)
	MQTT.DEBUG = log.New(os.Stdout, "", 0)

	quit := make(chan struct{})

	connOpts := MQTT.NewClientOptions()
	connOpts.AddBroker("tcp://127.0.0.1:1883")
	connOpts.SetAutoReconnect(true)
	connOpts.SetCleanSession(true)
	connOpts.SetConnectionLostHandler(func(client MQTT.Client, err error) {
		close(quit)
	})
	client := MQTT.NewClient(connOpts)
	if token := client.Connect(); token.Wait() && token.Error() != nil {
		log.Println("connect", token.Error())
		return
	}
	log.Println("Stop mosquitto now, please.")
	select {
	case <-quit:
		log.Println("quit")
	}
	if client.IsConnected() {
		log.Println("disconnecting")
		client.Disconnect(5000)
	}
	log.Println("exit")
}
```

**Comment by anymark** [comment]
here is my log & trace
```
[client]   Connect()
[store]    memorystore initialized
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
[net]      connect started
[net]      received connack
[client]   client is connected
[store]    memorystore wiped
[client]   exit startClient
2016/08/17 13:50:42 Stop mosquitto now, please.
[net]      outgoing started
[net]      outgoing waiting for an outbound message
[net]      logic started
[net]      logic waiting for msg on ibound
[pinger]   keepalive starting
[net]      incoming started
[net]      incoming stopped with error EOF
[net]      logic received from error channel, other components have errored, stopping
[pinger]   keepalive stopped
[net]      outgoing stopped
2016/08/17 13:50:45 quit
[client]   enter reconnect
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1.1 protocol
2016/08/17 13:50:45 disconnecting
[client]   disconnecting
[net]      connect started
[net]      connect got error EOF
[client]   Trying reconnect using MQTT 3.1 protocol
[client]   about to write new connect msg
[client]   socket connected to broker
[client]   Using MQTT 3.1 protocol
[net]      connect started
[net]      connect got error read tcp 127.0.0.1:60882->127.0.0.1:1883: read: connection reset by peer
[client]   Reconnect failed, sleeping for 1 seconds
[client]   about to write new connect msg
[client]   dial tcp 127.0.0.1:1883: getsockopt: connection refused
[client]   failed to connect to broker, trying next
[client]   Reconnect failed, sleeping for 2 seconds
[client]   about to write new connect msg
[client]   dial tcp 127.0.0.1:1883: getsockopt: connection refused
[client]   failed to connect to broker, trying next
[client]   Reconnect failed, sleeping for 4 seconds
In disconnect and stop channel is already closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46ce17]

goroutine 1 [running]:
panic(0x6fda00, 0xc42000c0b0)
        /home/mk/go1.7/src/runtime/panic.go:500 +0x1ae
github.com/eclipse/paho%2emqtt%2egolang.(*client).disconnect(0xc4200b8000)
        /home/mk/simulator/src/github.com/eclipse/paho.mqtt.golang/client.go:441 +0x67
github.com/eclipse/paho%2emqtt%2egolang.(*client).Disconnect(0xc4200b8000, 0x1388)
        /home/mk/simulator/src/github.com/eclipse/paho.mqtt.golang/client.go:394 +0x33e
main.main()
        /home/mk/simulator/src/mqtest/segv.go:36 +0x90e
exit status 2
```

**Comment by alsm** [comment]
The change above should resolve this issue, it works with your test case I'd appreciate you trying it with any other code you have that depends on it.

**Comment by anymark** [comment]
It seems to work well now. Thank you.
