### ISSUE TITLE
net.Conn nil check 

### ISSUE THREAD

**Issue by kylycht** [eclipse/paho.mqtt.golang#94]
When there is an error opening connection, goroutine panics:

```
conn, err := tls.DialWithDialer(&net.Dialer{Timeout: timeout}, "tcp", uri.Host, tlsc)
if err != nil {
	return nil, err
}
```
```
if rc != packets.Accepted {
	c.conn.Close()
        c.conn = nil
```
causing line: https://github.com/eclipse/paho.mqtt.golang/blob/master/client.go#L175
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x814341b]
goroutine 53 [running]:
panic(0x83ac7e0, 0x1880a018)
	/Users/tkila/.gvm/gos/go1.7.4/src/runtime/panic.go:500 +0x331
github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1(0x188f81e0, 0x18ab1960, 0x18adb470)
	/Users/tkila/.gvm/pkgsets/go1.7.4/global/src/github.com/eclipse/paho.mqtt.golang/client.go:193 +0x61b
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect
	/Users/tkila/.gvm/pkgsets/go1.7.4/global/src/github.com/eclipse/paho.mqtt.golang/client.go:269 +0x16e
```

**Comment by alsm** [comment]
Thanks for reporting this, I hadn't considered the possibility that the connect could have failed because the connection had already dropped. I've added a nil check on the conn at the appropriate place.
